### ISSUE TITLE
[QUESTION] SRAdb up to date?

### ISSUE THREAD

**Issue by snayfach** [saketkc/pysradb#157]
I recall that SRAdb was no longer being maintained and also noticed that some recent SRA accessions (ex: ERR6349793) are missing from the sqlite3 database: https://s3.amazonaws.com/starbuck1/sradb/SRAmetadb.sqlite.gz. Is this still the source of SRA metadata used by pysradb?

**Comment by saketkc** [comment]
No, pysradb uses NCBI's web API. A bit unfortunate in hindsight that the name of this package was dervied from SRAdb - to which it now has absolutely no relation/dependence.

**Comment by snayfach** [comment]
Thanks for the quick response! I had read that in your F1000 article: https://f1000research.com/articles/8-532

Is it possible to use pysradb to get metadata for all runs in the SRA? Any recommendations for that?

**Comment by saketkc** [comment]
I was considering an update to the article to reflect some of the new functionalities we added over the last couple of years, particularly with @bscrow's search functionality.

It is currently not possible to get all the metadata since NCBI's api will time out. There are dumps available here that might be helpful: https://ftp.ncbi.nlm.nih.gov/sra/reports/Metadata/

**Comment by snayfach** [comment]
I'm aware of those, but it's a big pain since there are million of XML files. Thanks for the responses.

**Comment by saketkc** [comment]
Right, I know it's frustrating. There seems to be some code available to ease the process (that I have not tested): https://github.com/linsalrob/SRA_Metadata
