### ISSUE TITLE
KeyError: 'run_accession'

### ISSUE THREAD

**Issue by ChongLC** [saketkc/pysradb#167]
I tried testing running SRAweb using Colab for `SRR11378996`. It popped out an error (as shown below). 
![image](https://user-images.githubusercontent.com/51225708/201354277-16af51fd-1f53-48fd-9497-cb52006a416b.png)

While checking the ncbi SRA, it provides the information as shown here: https://www.ncbi.nlm.nih.gov/sra/?term=SRR11378996. 

May I know how should I solve this? 

Looking forward to hearing from you. Thank you. 

Regards, 
Chong

**Comment by saketkc** [comment]
Thank you for the bug report. I have pushed a fix in https://github.com/saketkc/pysradb/commit/bb6d46226c04234b30eaa935cd6644c8f9cbce3f

Unfortunately for this project NCBI does not return all the run ids (possibly because there are 700+), so only experiment accession and related metadata is reported. See notebook here: https://colab.research.google.com/drive/1Z_lrhf3hUru1nBbLKoPeHM6RLxidiyni?usp=sharing

**Comment by ChongLC** [comment]
Thank you for the explanation @saketkc!
